### ISSUE TITLE
Fix tests in `bgnpcgn-bul-Cyrl-Latn-2013`

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#22]
1. "София" should be transliterated as "Sofia", but it is now "Sofiya".

```ruby
  20) Interscript maps/bgnpcgn-bul-Cyrl-Latn-2013.yaml system test for {"source"=>"София", "expected"=>"Sofia"}
      Failure/Error: expect(result).to eq(test["expected"])
        expected: "Sofia"
             got: "Sofiya"
        (compared using ==)
      # ./spec/interscript_spec.rb:13:in `block (5 levels) in <top (required)>'
```

2. "София-Град" should be transliterated as "Sofia-Grad", but it is now "Sofiya-Grad".

```ruby
  21) Interscript maps/bgnpcgn-bul-Cyrl-Latn-2013.yaml system test for {"source"=>"София-Град", "expected"=>"Sofia-Grad"}
Failure/Error: expect(result).to eq(test["expected"])
  expected: "Sofia-Grad"
       got: "Sofiya-Grad"
  (compared using ==)
# ./spec/interscript_spec.rb:13:in `block (5 levels) in <top (required)>'

```

**Comment by ronaldtse** [comment]
@andrew2net thanks for fixing this. I'm thinking that do we need some "post processing" step? e.g. after transliterating "Sofiya", we can convert it to "Sofia" by matching the closing position.

**Comment by andrew2net** [comment]
@ronaldtse we can add postprocessing rules, but this case could be easily solved by the rules we already have.
