### ISSUE TITLE
Fix paragraph test in `bas-rus-Cyrl-Latn-{bss,oss}`

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#23]
For both `bas-rus-Cyrl-Latn-oss` and `bas-rus-Cyrl-Latn-bss` systems.

The test expectation is correct, but the transliteration isn't. This seems related to #17.

```ruby
  15) Interscript maps/bas-rus-Cyrl-Latn-bss.yaml system test for {"source"=>"Эх, тройка! птица тройка, кто тебя выдумал? знать, у бойкого народа ты могла только родиться, в той земле, что не любит шутить, а ровнем-гладнем разметнулась на полсвета, да и ступай считать версты, пока не зарябит тебе в очи. И не хитрый, кажись, дорожный снаряд, не железным схвачен винтом, а наскоро живьём с одним топором да долотом снарядил и собрал тебя ярославский расторопный мужик. Не в немецких ботфортах ямщик: борода да рукавицы, и сидит чёрт знает на чём; а привстал, да замахнулся, да затянул песню — кони вихрем, спицы в колесах смешались в один гладкий круг, только дрогнула дорога, да вскрикнул в испуге остановившийся пешеход — и вон она понеслась, понеслась, понеслась!\nН.В. Гоголь", "expected"=>"Eh, troyka! ptitsa troyka, kto tebya vidumal? znat, u boykogo naroda ti mogla tolko roditsya, v toy zemle, chto ne lyubit shutit, a rovnem-gladnem razmetnulas na polsveta, da i stupay schitay versti, poka ne zaryabit tebe v ochi. I ne hitriy, kazhis, dorozhniy snaryad, ne zheleznim shvachen vintom, a naskoro zhivyem s odnim toporom da dolotom sobral tebya yaroslavskiy rastoropniy muzhik. Ne v nemetskih botfortah yamshchik: boroda da rukavitsi, i sidit chert znaet na chem; a privstal, da zamahnulsya, da zatyanul pesnyu — koni vihrem, spitsi v kolesah smeshalis v odin gladkiy krug, tolko drognula doroga, da vskriknul v ispuge ostanovivshiysya peshehod — i von ona poneslas, poneslas, poneslas!\nN.V. Gogol"}
      Failure/Error: expect(result).to eq(test["expected"])
      
        expected: "Eh, troyka! ptitsa troyka, kto tebya vidumal? znat, u boykogo naroda ti mogla tolko roditsya, v toy ... vskriknul v ispuge ostanovivshiysya peshehod — i von ona poneslas, poneslas, poneslas!\nN.V. Gogol"
             got: "Eh, troyka! ptitsa troyka, kto tebya vidumal? znat, u boykogo naroda ti mogla tolko roditsya, v toy ... vskriknul v ispuge ostanovivshiysya peshehod — i von ona poneslas, poneslas, poneslas!\nN.V. Gogol"
      
        (compared using ==)
      
        Diff:
        @@ -1,3 +1,3 @@
        -Eh, troyka! ptitsa troyka, kto tebya vidumal? znat, u boykogo naroda ti mogla tolko roditsya, v toy zemle, chto ne lyubit shutit, a rovnem-gladnem razmetnulas na polsveta, da i stupay schitay versti, poka ne zaryabit tebe v ochi. I ne hitriy, kazhis, dorozhniy snaryad, ne zheleznim shvachen vintom, a naskoro zhivyem s odnim toporom da dolotom sobral tebya yaroslavskiy rastoropniy muzhik. Ne v nemetskih botfortah yamshchik: boroda da rukavitsi, i sidit chert znaet na chem; a privstal, da zamahnulsya, da zatyanul pesnyu — koni vihrem, spitsi v kolesah smeshalis v odin gladkiy krug, tolko drognula doroga, da vskriknul v ispuge ostanovivshiysya peshehod — i von ona poneslas, poneslas, poneslas!
        +Eh, troyka! ptitsa troyka, kto tebya vidumal? znat, u boykogo naroda ti mogla tolko roditsya, v toy zemle, chto ne lyubit shutit, a rovnem-gladnem razmetnulas na polsveta, da i stupay schitat versti, poka ne zaryabit tebe v ochi. I ne hitriy, kazhis, dorozhniy snaryad, ne zheleznim shvachen vintom, a naskoro zhivyeem s odnim toporom da dolotom snaryadil i sobral tebya yaroslavskiy rastoropniy muzhik. Ne v nemetskih botfortah yamshchik: boroda da rukavitsi, i sidit chert znaet na chem; a privstal, da zamahnulsya, da zatyanul pesnyu — koni vihrem, spitsi v kolesah smeshalis v odin gladkiy krug, tolko drognula doroga, da vskriknul v ispuge ostanovivshiysya peshehod — i von ona poneslas, poneslas, poneslas!
         N.V. Gogol
        
      # ./spec/interscript_spec.rb:13:in `block (5 levels) in <top (required)>'

...

  34) Interscript maps/bas-rus-Cyrl-Latn-oss.yaml system test for {"source"=>"Эх, тройка! птица тройка, кто тебя выдумал? знать, у бойкого народа ты могла только родиться, в той земле, что не любит шутить, а ровнем-гладнем разметнулась на полсвета, да и ступай считать версты, пока не зарябит тебе в очи. И не хитрый, кажись, дорожный снаряд, не железным схвачен винтом, а наскоро живьём с одним топором да долотом снарядил и собрал тебя ярославский расторопный мужик. Не в немецких ботфортах ямщик: борода да рукавицы, и сидит чёрт знает на чём; а привстал, да замахнулся, да затянул песню — кони вихрем, спицы в колесах смешались в один гладкий круг, только дрогнула дорога, да вскрикнул в испуге остановившийся пешеход — и вон она понеслась, понеслась, понеслась!\nН.В. Гоголь", "expected"=>"`Eh, troyka! ptitsa troyka, kto tebya v`idumal? znat', u boykogo naroda t`i mogla tol'ko rodit'sya, v toy zemle, chto ne lyubit shutit', a rovnem-gladnem razmetnulas' na polsveta, da i stupay schitay verst`i, poka ne zaryabit tebe v ochi. I ne hitr`iy, kazhis', dorozhn`iy snaryad, ne zhelezn`im shvachen vintom, a naskoro zhivy``em s odnim toporom da dolotom sobral tebya yaroslavskiy rastoropn`iy muzhik. Ne v nemetskih botfortah yamshchik: boroda da rukavits`i, i sidit ch``ert znaet na ch``em; a privstal, da zamahnulsya, da zatyanul pesnyu — koni vihrem, spits`i v kolesah smeshalis' v odin gladkiy krug, tol'ko drognula doroga, da vskriknul v ispuge ostanovivshiysya peshehod — i von ona poneslas', poneslas', poneslas'!\nN.V. Gogol'"}
      Failure/Error: expect(result).to eq(test["expected"])
      
        expected: "`Eh, troyka! ptitsa troyka, kto tebya v`idumal? znat', u boykogo naroda t`i mogla tol'ko rodit'sya, ...riknul v ispuge ostanovivshiysya peshehod — i von ona poneslas', poneslas', poneslas'!\nN.V. Gogol'"
             got: "`Eh, troyka! ptitsa troyka, kto tebya v`idumal? znat', u boykogo naroda t`i mogla tol'ko rodit'sya, ...riknul v ispuge ostanovivshiysya peshehod — i von ona poneslas', poneslas', poneslas'!\nN.V. Gogol'"
      
        (compared using ==)
      
        Diff:
        @@ -1,3 +1,3 @@
        -`Eh, troyka! ptitsa troyka, kto tebya v`idumal? znat', u boykogo naroda t`i mogla tol'ko rodit'sya, v toy zemle, chto ne lyubit shutit', a rovnem-gladnem razmetnulas' na polsveta, da i stupay schitay verst`i, poka ne zaryabit tebe v ochi. I ne hitr`iy, kazhis', dorozhn`iy snaryad, ne zhelezn`im shvachen vintom, a naskoro zhivy``em s odnim toporom da dolotom sobral tebya yaroslavskiy rastoropn`iy muzhik. Ne v nemetskih botfortah yamshchik: boroda da rukavits`i, i sidit ch``ert znaet na ch``em; a privstal, da zamahnulsya, da zatyanul pesnyu — koni vihrem, spits`i v kolesah smeshalis' v odin gladkiy krug, tol'ko drognula doroga, da vskriknul v ispuge ostanovivshiysya peshehod — i von ona poneslas', poneslas', poneslas'!
        +`Eh, troyka! ptitsa troyka, kto tebya v`idumal? znat', u boykogo naroda t`i mogla tol'ko rodit'sya, v toy zemle, chto ne lyubit shutit', a rovnem-gladnem razmetnulas' na polsveta, da i stupay schitat' verst`i, poka ne zaryabit tebe v ochi. I ne hitr`iy, kazhis', dorozhn`iy snaryad, ne zhelezn`im shvachen vintom, a naskoro zhivy``e``em s odnim toporom da dolotom snaryadil i sobral tebya yaroslavskiy rastoropn`iy muzhik. Ne v nemetskih botfortah yamshchik: boroda da rukavits`i, i sidit ch``ert znaet na ch``em; a privstal, da zamahnulsya, da zatyanul pesnyu — koni vihrem, spits`i v kolesah smeshalis' v odin gladkiy krug, tol'ko drognula doroga, da vskriknul v ispuge ostanovivshiysya peshehod — i von ona poneslas', poneslas', poneslas'!
         N.V. Gogol'
        
      # ./spec/interscript_spec.rb:13:in `block (5 levels) in <top (required)>'

```

**Comment by andrew2net** [comment]
@ronaldtse I think the expectation is incorrect: `считать` is converted to `schitat'`, which is correct, but expectation is `schitay`.

**Comment by ronaldtse** [comment]
Let me provide the actual PDF here, please fix them if inaccurate.

[bas-rus-Cyrl-Latn.pdf](https://github.com/riboseinc/interoperable-transliteration/files/3886294/bas-rus-Cyrl-Latn.pdf)

Russian Cyrillic:

<img width="765" alt="Screen Shot 2019-11-25 at 7 07 03 PM" src="https://user-images.githubusercontent.com/11865/69535482-07a66a80-0fb7-11ea-9590-b39262b5f17f.png">

<img width="724" alt="Screen Shot 2019-11-25 at 7 07 16 PM" src="https://user-images.githubusercontent.com/11865/69535493-0ecd7880-0fb7-11ea-9d87-2ed5854c5d33.png">

We should also add those individual samples:
<img width="726" alt="Screen Shot 2019-11-25 at 7 07 33 PM" src="https://user-images.githubusercontent.com/11865/69535513-18ef7700-0fb7-11ea-9a3b-361791fd8caf.png">

**Comment by ronaldtse** [comment]
(`oss` is the Optimized Streamlined System, `bss` is the Basic Streamlined System)

**Comment by andrew2net** [comment]
@ronaldtse I've seen the PDF but can't find map `ть` => `y` in it.

**Comment by andrew2net** [comment]
In the Optimized Streamlined System, I see `ь (before е, ё, и, o, э) → y, ь (otherwise) →' (or none)` only.
In the Basic Streamlined System `ь (before е, ё, и, o, э) → y, ь (otherwise) → (none)` only.

**Comment by ronaldtse** [comment]
Agree, can't find out why this is a problem. I'm asking the author of the system now.

**Comment by ronaldtse** [comment]
But in any case, could you help add the individual word test cases for both BSS and OSS? Thanks.

**Comment by andrew2net** [comment]
Yes, there are other issues in the test cases. I'm working on them.

**Comment by andrew2net** [comment]
@ronaldtse There is one more mistake in this expectation:
`долотом снарядил и собрал` converts to `dolotom snaryadil i sobral` but the expectation is `dolotom sobral`. In this case the expectation miss 2 words.

**Comment by ronaldtse** [comment]
@andrew2net the author confirmed that both `schitat'` (OS), `schitat` (BS) and the two missing words were errors. Can you please help fix them? Thanks!
